disallowed-types = [
    { path = "std::collections::HashMap", reason = "use fxhash::FxHashMap" },
    { path = "std::collections::HashSet", reason = "use fxhash::FxHashSet" },
    { path = "std::collections::hash_map::RandomState", reason = "use fxhash::BuildHasherDefault<FxHasher>" },
    { path = "std::sync::Mutex", reason = "use parking_lot::Mutex" },
    { path = "std::sync::RwLock", reason = "use parking_lot::RwLock" }
]

disallowed-methods = []

# Allow these words in doc comments and item names
doc-valid-idents = [
    "xtask",
    "muster"
]

# Limit the complexity of functions
too-many-lines-threshold = 100
# Avoid complex types in signatures
type-complexity-threshold = 250