[advisories]
ignore = [
    "RUSTSEC-2025-0140",
    "RUSTSEC-2024-0370",
    "RUSTSEC-2024-0436",
    "RUSTSEC-2024-0384",
    "RUSTSEC-2024-0419",
    "RUSTSEC-2024-0420",
    "RUSTSEC-2024-0415",
    "RUSTSEC-2024-0411",
    "RUSTSEC-2024-0418",
    "RUSTSEC-2024-0412",
    "RUSTSEC-2025-0057",
    "RUSTSEC-2025-0141",
    "RUSTSEC-2023-0089",
    "RUSTSEC-2024-0416",
    "RUSTSEC-2024-0413",
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-DFS-2016",
    "BSL-1.0",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
    "CC0-1.0",
    "Apache-2.0 WITH LLVM-exception",
    "BUSL-1.1",
    "MPL-2.0",
    "Unlicense",
    "OpenSSL",
]
confidence-threshold = 0.7