[package]
name = "mhub"
description = "Feature Gateway Crate (Facade)"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []

# Platform features
server = [
    "mhub-kernel/server",
    "dep:mhub-licensing",
    "mhub-identity/server",
    "mhub-audit/server",
    "mhub-organization/server",
]
client = [
    "mhub-kernel/client",
    "mhub-identity/client",
]

# Optional features (can be disabled at compile time)
full = ["default", "server", "client"]

[dependencies]
mhub-kernel.workspace = true
mhub-domain.workspace = true
mhub-identity.workspace = true
mhub-event-bus.workspace = true
mhub-audit = { workspace = true, optional = true }
mhub-organization = { workspace = true, optional = true }
mhub-licensing = { workspace = true, optional = true }
mhub-database.workspace = true

[lib]
name = "mhub"
path = "src/lib.rs"

[lints]
workspace = true
